app/blog/forms.py
import wtforms as wtf
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired, Length


class _PostProcessingForm(FlaskForm):
    """General form for post creating and editing"""

    post_title = wtf.StringField()
    post_body = wtf.TextAreaField()
    post_tags = wtf.StringField("Post tags (optional)")


class PostCreateForm(_PostProcessingForm):
    """Form for post creating"""

    post_submit = wtf.SubmitField("Add post")


class PostEditForm(_PostProcessingForm):
    """Form for post editing"""

    post_submit = wtf.SubmitField("Edit post")


class CommentForm(FlaskForm):
    """Form for post commenting"""

    comment_body = wtf.TextAreaField(
        "Write your comment...",
        validators=[InputRequired("The area must be filled!"), Length(min=5)],
    )
    submit = wtf.SubmitField("Add comment")

app/blog/__init__.py
from . import blueprint

app/blog/blueprint.py
import flask
import flask_login as flog

from . import funcs


blog = flask.Blueprint("blog", __name__)


@blog.route("/js-file/<path:filename>")
def get_js_file(filename: str) -> flask.Response:
    """For getting js file from 'static' folder"""
    return funcs.get_js_file(filename)


@blog.route("/")
def get_blog_page() -> str:
    """For getting the 'blog' page"""
    return funcs.get_blog_page()


@blog.route("/create-post", methods=["GET", "POST"])
@flog.login_required
def create_post() -> str:
    """
    GET: getting the page for creating post
    POST: creating post
    """
    return funcs.create_post()


@blog.route("/tag/<tag>")
def get_all_posts_with_(tag: str) -> str:
    """For getting all posts by tag"""
    return funcs.get_all_posts_with_(tag)


@blog.route("/post/<post_url>")
def get_post_by_(post_url: str) -> str:
    """For getting the post page"""
    return funcs.get_post_by_(post_url)


@blog.route("/post/<post_url>/delete")
@flog.login_required
def delete_post_with_(post_url: str) -> flask.Response:
    """For deleting post by post url"""
    return funcs.delete_post_with_(post_url)


@blog.route("/post/<post_url>/like", methods=["POST"])
@flog.login_required
def like_post_with_(post_url: str) -> str:
    """For getting json with data for post liking"""
    return funcs.like_post()


@blog.route("/post/<post_url>/comment", methods=["POST"])
@flog.login_required
def comment_post_with_(post_url: str) -> flask.Response:
    """For post commenting"""
    return funcs.comment_post_with_(post_url)


@blog.route("/post/<post_url>/delete-comment/<int:comment_id>")
@flog.login_required
def delete_comment_with_(post_url: str, comment_id: int) -> flask.Response:
    """For deleting comment by id for post by post url"""
    return funcs.delete_comment_with_(post_url, comment_id)


@blog.route("/post/<post_url>/edit", methods=["GET", "POST"])
@flog.login_required
def edit_post_with_(post_url: str) -> str | flask.Response:
    """
    GET: getting the page for post editing
    POST: post editing
    """
    return funcs.edit_post_with_(post_url)

app/templates/blog/_blog.html
{%- extends 'base.html' %} 

{%- block title -%} Blog {%- endblock -%} 


{%- block content -%}

<div
	class="site-header sticky-top py-2 d-flex justify-content-end mb-4 border-2 border-bottom border-info my-text-color my-body-bg-color"
>
	<div class="btn-group btn-group-lg">
        {% set tab = request.args.get('tab') %} 

		<a
			href="./?tab=posts"
            {%- if not tab or tab == "posts" %}
                class="btn btn-primary active disabled"
                aria-current="page"
            {%- else %}
                class="btn btn-primary"
            {%- endif %}
		>
            Posts
        </a>
		<a
			href="./?tab=tags"
			{%- if tab == "tags" %}
                class="btn btn-primary active disabled"
                aria-current="page"
            {%- else %}
                class="btn btn-primary"
            {%- endif %}
		>
            Tags
        </a>
	</div>
</div>

{%- endblock content -%}

app/templates/blog/_pagination.html
{%- if request.args.get('q', '') %}
    {% set needed_url = "?q=" + request.args.get('q') + "&" %}
{%- else %}
    {% set needed_url = "?" %}
{%- endif %}

<nav class="d-flex justify-content-center mt-4">
	<ul class="pagination pagination-sm">
		<li
			class="page-item {%- if not posts.has_prev %} disabled {%- endif %}"
		>
			<a
				class="page-link"
				href="./{{ needed_url }}page={{ posts.prev_num }}"
			>
				&laquo;
			</a>
		</li>

		{%- for page in posts.iter_pages(left_edge=1, left_current=1, right_current=1, right_edge=1) %}
            {%- if page == None %}
            <li
                class="page-item disabled"
            >
                <a
                    href=""
                    class="page-link"
                >
                    ...
                </a>
            </li>
            {%- else %}
            <li class="page-item {%- if page == posts.page %} active {%- endif %}">
                <a
                    class="page-link"
                    href="./{{ needed_url }}page={{ page }}"
                >
                    {{ page }}
                </a>
            </li>
            {%- endif %}
		{%- endfor %}

		<li
			class="page-item {%- if not posts.has_next %} disabled {%- endif %}"
		>
			<a
				class="page-link"
				href="./{{ needed_url }}page={{ posts.next_num }}"
			>
				&raquo;
			</a>
		</li>
	</ul>
</nav>

app/templates/blog/_post_macros.html
{%- macro show_all_posts_from_(posts, current_user_id) %}

{%- for post in posts %}
    <div class="post rounded my-form-bg-color p-3 mb-3">
        <a href="{{ url_for('blog.get_post_by_', post_url=post.url) }}">
            <div 
                class="post_title text-decoration-underline d-flex justify-content-between"
            >
                <h3>{{ post.title }}</h3>
                {%- if post.user.id == current_user_id %} 
                    <a 
                        class="btn-close btn-close-white delete-btn"
                        href="{{ 
                            url_for(
                                'blog.delete_post_with_', 
                                post_url=post.url,
                                next=request.url
                            ) 
                        }}"
                    ></a>
                {%- endif %}
            </div>
            <div class="post_body py-2">
                <p>{{ post.body[:200] | striptags }}...</p>
            </div>
        </a>

        {{ show_info_about_(post) }}
    </div>
{%- endfor %} 

{%- endmacro %} 


{%- macro show_info_about_(item, show_in_profile=False) %}

<div class="item_info d-flex justify-content-between">
    <div class="item_author me-3">
        {%- if show_in_profile %}
            <b>For post:</b> &nbsp;
            <a
                href="{{
                    url_for(
                        'blog.get_post_by_',
                        post_url=item.post.url
                    )
                }}"
                class="text-decoration-underline"
            >
                {{ item.post.url }}
            </a>
        {%- else %}
            <b>Author:</b> &nbsp; 
            <a 
                href="{{ 
                    url_for(
                        'profile.get_user_with_', 
                        username=item.user.username
                    ) 
                }}"
                class="text-decoration-underline"
            >
                {{ item.user.username }}
            </a>
        {%- endif %}
    </div>
    <div class="item_created">
        <b>Created:</b> &nbsp; 
        {{ item.created.strftime("%d.%m.%Y") }}
    </div>
</div>

{%- endmacro %}


{%- macro show_all_tags_from_(tags) %}

{%- for tag in tags %}
    <a
        class="d-inline float_left me-3 mb-3 text-decoration-none"
        href="{{ url_for('blog.get_all_posts_with_', tag=tag.url) }}"
    >
        <span 
            style="line-height: 1.5em;"
            class="tag badge border rounded"
        >#{{ tag.title }}</span>
    </a>
{%- endfor %}

{%- endmacro %} 


{%- macro show_all_comment_from_(comments, current_user_id, show_in_profile=False) %}
    
{%- for comment in comments %}
    <div class="alert alert-dark" role="alert">
        <div class="d-flex justify-content-between">
            <p>{{ comment.body }}</p>

            {%- if comment.user.id == current_user_id %} 
                <a 
                    class="btn-close delete-btn"
                    href="{{ 
                        url_for(
                            'blog.delete_comment_with_', 
                            post_url=comment.post.url, 
                            comment_id=comment.id,
                            next=request.url
                        ) 
                    }}"
                ></a>
            {%- endif %}
        </div>
        
        {{ show_info_about_(comment, show_in_profile) }}
    </div>
{%- endfor %} 

{%- endmacro %} 

app/templates/blog/all_posts.html
{%- extends 'blog/_blog.html' %}

{%- block styles -%}
    <style>
        .search { max-width: 70%; }

        @media screen and (max-width: 576px) {
            .search_form { margin-bottom: 25px; }
        }

        .item_info { color: white; }
    </style>
{%- endblock styles -%}

{%- block content_title -%}
{%- if request.args.get("q", "") %} Results {%- else %} All posts ({{ posts_count }}) {%- endif %}
{%- endblock -%}

{%- block search_form -%}
    {%- if posts.items or request.args.get("q", "")%}
        <form role="search" class="d-flex align-items-center">
            <input
                name="q"
                type="search"
                aria-label="Search"
                placeholder="Search"
			    value="{{ request.args.get('q', '') }}"
                class="form-control search me-2 ms-lg-3 ms-sm-0"
            />
            <button
                type="submit"
                class="btn btn-outline-success mt-1"
            >
                Search
            </button>
        </form>
    {%- endif %}
{%- endblock search_form -%}


{%- block content -%}

{{ super() }}

{%- if posts.items %}

    {%- from 'blog/_post_macros.html' import show_all_posts_from_ %}
    {{ show_all_posts_from_(posts.items, current_user.id) }}

    {%- if not posts.prev_num and not posts.next_num %}
        <!-- No pagination, it's only one page -->
    {%- else %}
        {%- include 'blog/_pagination.html' %}
    {%- endif %}

{%- else %}
    {%- from '_alerts_macros.html' import not_dismissible_alert %}

    {%- if request.args.get("q", "") %}
        {{
            not_dismissible_alert(
                message="There are not such posts with '"
                        + request.args.get('q', '') + "' yet",
                category="danger"
            )
        }}
    {%- else %}
        {{
            not_dismissible_alert(
                message="There are not any posts yet",
                category="primary"
            )
        }}
    {%- endif %}
{%- endif %}

{%- endblock content -%}


{%- block scripts -%}
<script>
    function resize_pagination() {
        let pagination = document.querySelector(".pagination");

        window.outerWidth >= 992
            ? pagination.classList.add("pagination-lg")
            : pagination.classList.remove("pagination-lg");

        window.outerWidth <= 768
            ? pagination.classList.add("pagination-sm")
            : pagination.classList.remove("pagination-sm");
    }

    resize_pagination();
    window.addEventListener("resize", resize_pagination);
</script>

<script src="{{ url_for('static', filename='js/delete_btn.js') }}"></script>
{%- endblock scripts -%}

app/templates/blog/all_tags.html
{%- extends 'blog/_blog.html' %}

{%- block styles -%}
<style>
    @media screen and (max-width: 452px) {
        .badge { font-size: 1em; }
    }
</style>
{%- endblock styles -%}

{%- block content_title -%} All tags ({{ tags | length }}) {%- endblock -%}


{%- block content -%}

{{ super() }}

{%- if tags %}
    <div class="tags d-flex flex-wrap justify-content-between">
        {%- from 'blog/_post_macros.html' import show_all_tags_from_ %}
        {{ show_all_tags_from_(tags) }}
    </div>
{%- else %}
    {%- from '_alerts_macros.html' import not_dismissible_alert %}
    {{
        not_dismissible_alert(
            message="There are not any tags yet",
            category="primary"
        )
    }}
{%- endif %}

{%- endblock content -%}


{%- block scripts -%}
<script src="{{ url_for('static', filename='js/blog/tags.js') }}"></script>
{%- endblock -%}

app/templates/blog/create_post.html
{%- extends 'base.html' %} 

{%- block title -%} Create post {%- endblock -%} 

{%- block styles -%}
<link 
    type='text/css' 
    rel='stylesheet' 
    href='{{ url_for("static", filename="css/blog/create_post.css") }}'
/>
{%- endblock styles -%}

{%- block content_title -%} Create post {%- endblock -%} 


{%- block content -%}

{%- block page_alert -%}  
    {%- from '_alerts_macros.html' import not_dismissible_alert %}
    
    {{
        not_dismissible_alert(
            message="Fill this area out using buttons below",
            category="primary"
        )
    }}
{%- endblock page_alert -%}

<details>
    <summary>How to create post? (Note)</summary>
    <div class="note-alert alert alert-secondary border-left" role="alert">
        <ul>
            <li>Make sure your title doesn't exist.</li>
            <li>
                Use special element buttons for: 
                <ul>
                    <li>editing;</li>
                    <li>deleting;</li>
                    <li>changing position;</li>
                    <li>changing alignment.</li>
                </ul>
            </li>
            <li>
                If you use a mobile device, click on any element to see special buttons.
            </li>
            <li>
                Use a comma as separator for post tags (optional).
            </li>
        </ul>
        <h5>Good luck!</h5>
    </div>
</details>

{%- block post_title -%}{%- endblock -%} 

<div class="content border border-dark rounded py-2 my-3">
    {%- block post_body -%}{%- endblock -%} 
</div>

<div class="my-3 adding_buttons">
    <button
        id="add_subtitle1_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Subtitle I
    </button>
    <button
        id="add_subtitle2_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Subtitle II
    </button>
    <button
        id="add_paragraph_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Paragraph &nbsp;
        <ion-icon name="reorder-four-outline"></ion-icon>
    </button>
    <button
        id="add_link_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Link &nbsp;
        <ion-icon name="link-outline"></ion-icon>
    </button>
    <button
        id="add_code_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Code &nbsp;
        <ion-icon name="code-outline"></ion-icon>
    </button>
    <button
        id="add_image_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Image &nbsp;
        <ion-icon name="image-outline"></ion-icon>
    </button>
    <button
        id="add_alert_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Alert &nbsp;
        <ion-icon name="alert-circle-outline"></ion-icon>
    </button>
    <button
        id="add_line_btn"
        class="btn btn-lg btn-primary mb-2 me-2"
    >
        Line &nbsp;
        <ion-icon name="remove-outline"></ion-icon>
    </button>
</div>

<div class="my-3 processing_form">
    {%- from '_forms_macros.html' import render_field, render_field_with_errors %}

    <form 
        action="" 
        method="post"
        class="d-flex justify-content-between align-items-center"
    >
        <div>
            {{ form.hidden_tag() }}
            <!-- Invisible form fields -->
            {{ render_field(form.post_title, class="d-none") }}
            {{ render_field(form.post_body, class="d-none") }}
            <!-- Visible form fields -->
            {{ render_field_with_errors(form.post_tags, class="form-control") }}
        </div>
        <div>
            {{ render_field(form.post_submit, class="btn btn-success btn-lg mt-2") }}
        </div>
    </form>
    <p>Separator - comma</p>
</div>

{%- endblock content -%} 


{%- block scripts -%}
<script
    type="module"
    src="{{ url_for('blog.get_js_file', filename='blog/create_post.js') }}"
></script>
{%- endblock scripts -%} 

app/templates/blog/edit_post.html
{%- extends 'blog/create_post.html' %} 

{%- block title -%} Edit post {%- endblock -%}

{%- block content_title -%} Edit post {%- endblock -%} 

{%- block page_alert -%}  
    {%- from '_alerts_macros.html' import not_dismissible_alert %}
    
    {{
        not_dismissible_alert(
            message="If you want, you can change or add some elements",
            category="primary"
        )
    }}
{%- endblock page_alert -%}


{%- block post_title -%} <h2 id="title">{{ post.title }}</h2> {%- endblock -%}
{%- block post_body -%} {{ post.body | safe }} {%- endblock -%}


{%- block scripts -%}
{{ super() }}

<script>
    let post_tags = "{{ post.tags | map(attribute='title') | list | join(', ') }}";

    const post_tags_field = document.querySelector("#post_tags");
    post_tags_field.value = post_tags;
</script>

<script
type="module"
src="{{ url_for('blog.get_js_file', filename='blog/edit_post.js') }}"
></script>
{%- endblock scripts -%} 

app/templates/blog/post.html
{%- extends 'base.html' %} 

{%- block title -%} Post - {{ post.title }} {%- endblock -%} 

{%- block styles -%}
<style>
    #edit-btn { width: 50px; }

    .tag { background-color: var(--bs-primary); }

    #like-icon { color: red; }

    .item_author a { color: var(--my-text-color); }

    .share-links .links { font-size: 1.5em; }
    
    @media screen and (max-width: 576px) {
        .share-links .links { font-size: 1em; }
    }

    #comment_body { height: 150px; }

    .all-comments .item_author a { color: var(--bs-dark); }
</style>
{%- endblock styles -%} 

{%- block content_title -%} {{ post.title }} {%- endblock -%} 

{%- block near_content_title -%}
    {%- if current_user.id == post.user.id %}
        <a 
            id="edit-btn"
            href="{{ url_for('blog.edit_post_with_', post_url=post.url) }}" 
            class="btn btn-primary mb-3 d-flex justify-content-center align-items-center"
        >
            <ion-icon name="pencil"></ion-icon>
        </a>
    {%- endif %}
{%- endblock near_content_title -%} 


{%- block content -%} 

<div class="tags_and_likes mb-2 d-flex justify-content-between align-items-center">
    <div class="tags">
        {%- if post.tags %}
            {%- from 'blog/_post_macros.html' import show_all_tags_from_ %} 
            {{ show_all_tags_from_(post.tags) }}
        {%- else %}
            <span class="rounded text-bg-warning px-2 py-1">There are not any tags yet</span>
        {%- endif %}
    </div>
    <div class="likes"> 
        <button 
            type="button" 
            id="like-button"
            class="btn position-relative border-0"
            {%- if not current_user.is_authenticated %}disabled{%- endif %}
        >
            {%- if current_user.is_authenticated and not current_user.id in post.likes.all() | map(attribute="user_id") | list %}
                {% set icon_name = "-outline" %} 
            {%- endif %}

            <ion-icon 
                id="like-icon"
                name="heart{{ icon_name }}"
            ></ion-icon>
            <span 
                id="like-count"
                class="position-absolute top-0 start-100 translate-middle badge rounded-pill my-form-bg-color"
            >
                {{ post.likes.all() | length }}
            </span>
        </button>
    </div>
</div>

<hr>
{%- from 'blog/_post_macros.html' import show_info_about_ %}
{{ show_info_about_(post) }}
<hr class="mt-3">

{{ post.body | safe }}

<div class="share-links d-flex justify-content-center mt-2">
    <div class="links d-flex align-items-center my-2">
        <!-- Share link for Telegram -->
        <a 
            target="_blank"
            class="float_left me-4"
            href="https://t.me/share/url?url={{ request.url }}" 
        >
            <ion-icon name="send"></ion-icon>
        </a>
        <!-- Share link for Facebook -->
        <a 
            target="_blank"
            class="float_left me-4"
            href="https://www.facebook.com/sharer.php?u={{ request.url }}" 
        >
            <ion-icon name="logo-facebook"></ion-icon>
        </a>
        <!-- Share link for LinkedIn -->
        <a 
            target="_blank"
            class="float_left me-4"
            href="https://www.linkedin.com/sharing/share-offsite/?url={{ request.url }}" 
        >
            <ion-icon name="logo-linkedin"></ion-icon>
        </a>
        <!-- Share link for Email -->
        <a 
            target="_blank"
            href="mailto:?subject=Check-{{ post.title }}&body={{ request.url }}"
        >
            <ion-icon name="mail-outline"></ion-icon>
        </a>
    </div>
</div>

<hr class="my-2">

<h2 class="mb-3">Comments</h2>

{%- if current_user.is_authenticated %}
    <div class="comment-form w-100 mb-5">
        {%- from '_forms_macros.html' import get_ready_ %} 
        {{ 
            get_ready_(
                form, 
                action=url_for('blog.comment_post_with_', post_url=post.url)
            ) 
        }}
    </div> 
{%- else %}
    {%- from '_alerts_macros.html' import dismissible_alert %}
    {{
        dismissible_alert(
            message="Log in to has ability to comment post",
            category="warning"
        )
    }}
{%- endif %} 

{%- if post.comments.all() %}
    <div class="all-comments w-100">
        {%- from 'blog/_post_macros.html' import show_all_comment_from_ %}
        {{ 
            show_all_comment_from_(
                post.comments.order_by(desc("created")).all(),
                current_user.id
            ) 
        }}
    </div>
{%- else %}
    {%- from '_alerts_macros.html' import not_dismissible_alert %}
    {{
        not_dismissible_alert(
            message="There are not any comments yet",
            category="primary"
        )
    }}
{%- endif %} 

{%- endblock content -%} 


{%- block scripts -%}
<script>
    // Jinja2 variables for fetch "POST" request
    const post_url = "{{ post.url }}";

    const post_id = "{{ post.id }}";
    const user_id = "{{ current_user.id }}";
</script>

<script
type="module"
src="{{ url_for('blog.get_js_file', filename='blog/post.js') }}"
></script>

<script src="{{ url_for('static', filename='js/delete_btn.js') }}"></script>
{%- endblock scripts -%} 

app/templates/blog/tag.html
{%- extends 'base.html' %} 

{%- block title -%} #{{ tag.title }} {%- endblock -%} 

{%- block content_title -%} 
    Posts with '#{{ tag.title }}' ({{ tag.posts.all() | length }})
{%- endblock -%} 


{%- block content -%}

{%- if tag.posts.all() %}
    {%- from 'blog/_post_macros.html' import show_all_posts_from_ %}
    {{ show_all_posts_from_( tag.posts.all() ) }} 
{%- else %}
    {%- from '_alerts_macros.html' import not_dismissible_alert %} 
    {{ 
        not_dismissible_alert(
            message="There are not any posts with '#" + tag.title + "' yet",
            category="primary"
        ) 
    }}
{%- endif %}

{%- endblock content -%} 